############################################################################
# FoodLoop native hardware application
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = foodloop
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 12288
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_197_FOODLOOP)

MAINSRC = foodloop_main.c foodloop_ui.c

include $(APPDIR)/Application.mk
